spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    url: jdbc:mariadb://127.0.0.1:3306/boot_db?useUnicode=true&charaterEncoding=utf-8&useSSL=false&serverTimezone=UTC #4칸
    username: boot
    password: boot
    driver-class-name: org.mariadb.jdbc.Driver

  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: create #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸

        #ToMany 관계인 엔티티 객체를 조회할떼  IN구문의 파라미터 갯수
        default_batch_fetch_size: 1000 #100~1000사이 권장


logging.level: #띄어쓰기 없음
  org.hibernate.sql: debug #띄어쓰기 2칸
  #org.hibernate.type: trace #띄어쓰기 2칸

server:
    port: 8087